### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PowerPress** [e-ago/bitcracker#2]
This looks like an awesome project but I am confused on the process. What is an encrypted memory unit and exactly how do I get it. Assume I am looking at a PC right now what software/commands will I use to collect it? 

The next step would be to run bitcracker_hash against it and then finally bitcracker_cuda?

**Comment by e-ago** [comment]
If you want to do a complete test by yourself, you must have a Windows OS with BitLocker (To Go) installed (as specified in the main page of this project). For example, you can encrypt with BitLocker an USB flash drive using a password between 8 and 27 characters.
Then you need to run bitcracker_hash on the encrypted USB (you can extract the entire device image using tools like dd in Linux) and finally use the output hash as input of bitcracker_cuda (you need an NVIDIA GPU) or bitcracker_opencl (you can use GPU or CPU, but with a CPU performance are very slow). The input dictionary must contain the password you typed during encryption.

**Comment by PowerPress** [comment]
If I have my desktop encrypted using Bitlocker and its Win 7/Win 10 could I use this on it or does it only work on Bitlocker go encrypted portable hard drives/flash drives?

**Comment by e-ago** [comment]
I've improved the README with an extensive example, starting from the encrypted memory device.
If you are able to extract the image of your encrypted HD, you can use BitCracker.
