### ISSUE TITLE
Error while extracting data: No signature found!

### ISSUE THREAD

**Issue by ChrisLPJones** [e-ago/bitcracker#59]
i am trying to dump from a windows 11 .img and getting no results.

*log file

Encrypted device /dev/nvme0n1p3 opened, size 119917MB

*Command output

Signature found at 0x3
Version: 8 
Invalid version, looking for a signature with valid version...

Signature found at 0x6744000
Version: 2 (Windows 7 or later)

VMK entry found at 0x67440c3
VMK not encrypted.. stored clear! (0x67440e4)

VMK entry found at 0x2899e76d

Signature found at 0x721e2000
Version: 2 (Windows 7 or later)

VMK entry found at 0x721e20c3
VMK not encrypted.. stored clear! (0x721e20e4)

VMK entry found at 0xc4266e1a

VMK entry found at 0xed0a87ed

Signature found at 0x1c844d000
Version: 2 (Windows 7 or later)

VMK entry found at 0x1c844d0c3
VMK not encrypted.. stored clear! (0x1c844d0e4)

VMK entry found at 0x1d8c152fa

VMK entry found at 0x2e58c0509

VMK entry found at 0x5f0dc711a

VMK entry found at 0x6149d3ea1

VMK entry found at 0x69bf075e5

VMK entry found at 0x85940b0f0

VMK entry found at 0xdeb4c575a

VMK entry found at 0xebb1a74fa

VMK entry found at 0xf66744a97

VMK entry found at 0x13c753b8d5

VMK entry found at 0x1808d7ec73

VMK entry found at 0x18676141ff

VMK entry found at 0x1adf11f479

VMK entry found at 0x1b2e0c5a0c
Error while extracting data: No signature found!

**Comment by DramaKing19** [comment]
I'm getting results like this on a Windows 10 image created with dd. Bitlocker seems to be suspended, but I can't for the life of me figure out how to pull the clear key.
