### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by stevenliuit** [e-ago/bitcracker#8]
i build this project error：
i install xcode and cuda and modify src_cuda makefile is
 
![image](https://user-images.githubusercontent.com/4044994/44825019-352d2880-ac3b-11e8-922b-bf70e2e76205.png)

![image](https://user-images.githubusercontent.com/4044994/44825027-3e1dfa00-ac3b-11e8-8195-f006a28a7fea.png)

![image](https://user-images.githubusercontent.com/4044994/44825032-45dd9e80-ac3b-11e8-8ee5-a489137f0335.png)

![image](https://user-images.githubusercontent.com/4044994/44825036-4c6c1600-ac3b-11e8-98ed-f74ae72c8c70.png)

![image](https://user-images.githubusercontent.com/4044994/44825048-5b52c880-ac3b-11e8-9d30-b185964b4318.png)

StevendeiMac:bitcracker stevenbiu$ ./build.sh
====== Build BitCracker Hash Extractor ====== rm -rf *.o
rm -rf ../build/bitcracker_hash
gcc bitcracker_hash.c -o bitcracker_hash
run_tests.sh src_CUDA
run_tests.sh src_CUDA
====== Build BitCracker Recovery Password generator ====== rm -rf *.o
rm -rf ../build/bitcracker_rpgen
gcc bitcracker_rpgen.c -o bitcracker_rpgen
====== Build BitCracker CUDA version ======
rm -rf *.o
rm -rf ../build/bitcracker_cuda
nvcc -gencode arch=compute_70,code=sm_70 -Xptxas -v -o bitcracker_cuda main.cu cuda_attack.cu utils.cu w_blocks.cu make: nvcc: No such file or directory
make: *** [bitcracker_cuda] Error 1
====== Build BitCracker OpenCL version ======
rm -rf *.o
rm -rf bitcracker_opencl
gcc -I/usr/include -L/usr/lib64 -L/usr/lib -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -cl-std=CL1.2 -O3 -Wextra -o bitcracker_opencl main.c opencl_attack.c utils.c w_blocks.c -lOpenCL
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206: /usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not supported in OpenCL
#define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not supported in OpenCL #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not supported in OpenCL
#define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not supported in OpenCL #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not supported in OpenCL
#define __swift_compiler_version_at_least(...) 1 ^
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in OpenCL
#define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,__API_AVAILABLE5, __API_AVAILABLE4, __API_AVAILABLE3, __API_AVAILABLE2, __API_AVAILAB...

**Comment by stevenliuit** [comment]
StevendeiMac:bitcracker stevenbiu$ ./build.sh 

====== Build BitCracker Hash Extractor ======
rm -rf *.o
rm -rf ../build/bitcracker_hash
gcc bitcracker_hash.c -o bitcracker_hash

====== Build BitCracker Recovery Password generator ======
rm -rf *.o
rm -rf ../build/bitcracker_rpgen
gcc bitcracker_rpgen.c -o bitcracker_rpgen

====== Build BitCracker CUDA version ======
rm -rf *.o
rm -rf ../build/bitcracker_cuda
nvcc -gencode arch=compute_60,code=sm_60 -Xptxas -v -o bitcracker_cuda main.cu cuda_attack.cu utils.cu w_blocks.cu
nvcc fatal   : The version ('9.1') of the host compiler ('Apple clang') is not supported
make: *** [bitcracker_cuda] Error 1

====== Build BitCracker OpenCL version ======
rm -rf *.o
rm -rf bitcracker_opencl
gcc -I/usr/include -L/usr/lib64 -L/usr/lib -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -cl-std=CL1.2 -O3 -Wextra -o bitcracker_opencl main.c opencl_attack.c utils.c w_blocks.c -lOpenCL
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206:
/usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not supported in OpenCL
    #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
                                                          ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not supported in OpenCL
    #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not supported in OpenCL
    #define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not supported in OpenCL
    #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
                                                         ^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not supported in OpenCL
    #define __swift_compiler_version_at_least(...) 1
                                              ^
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in OpenCL
    #define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,__API_AVAILABLE5, __API_AVAILABLE4, __API_AVAILABLE3, __API_AVAILABLE2, __API_AVAILABLE1)(_...
                            ^
/usr/include/Availability.h:434:30: error: variadic macros not supported in OpenCL
    #define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO(__VA_ARGS__,__API_DEPRECATED_MSG6,__API_DEPRECATED_MSG5,__API_DEPRECATED_MSG4,__API_DEPRECATED_MS...
                             ^
/usr/include/Availability.h:435:47: error: variadic macros not supported in OpenCL

**Comment by stevenliuit** [comment]
i add nvcc
export PATH=/usr/local/cuda/bin:$PATH
DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH

**Comment by stevenliuit** [comment]
i install clt: 
nvcc fatal : The version ('9.1') of the host compiler ('Apple clang') is not supported
sudo xcode-select --switch /Library/Developer/CommandLineTools
but not fix this bug

**Comment by stevenliuit** [comment]
this new error:

StevendeiMac:bitcracker stevenbiu$ ./build.sh 

====== Build BitCracker Hash Extractor ======
rm -rf *.o
rm -rf ../build/bitcracker_hash
gcc bitcracker_hash.c -o bitcracker_hash

====== Build BitCracker Recovery Password generator ======
rm -rf *.o
rm -rf ../build/bitcracker_rpgen
gcc bitcracker_rpgen.c -o bitcracker_rpgen

====== Build BitCracker CUDA version ======
rm -rf *.o
rm -rf ../build/bitcracker_cuda
nvcc -gencode arch=compute_61,code=sm_61 -Xptxas -v -o bitcracker_cuda main.cu cuda_attack.cu utils.cu w_blocks.cu
ptxas info    : 0 bytes gmem, 12584 bytes cmem[3]
ptxas info    : 0 bytes gmem, 12584 bytes cmem[3]
ptxas info    : Compiling entry function '_Z20decrypt_vmk_with_maciPiPhS0_S0_S0_S0_iiiijjjji' for 'sm_61'
ptxas info    : Function properties for _Z20decrypt_vmk_with_maciPiPhS0_S0_S0_S0_iiiijjjji
    352 bytes stack frame, 484 bytes spill stores, 672 bytes spill loads
ptxas info    : Used 64 registers, 420 bytes cmem[0], 324 bytes cmem[2], 2 textures
ptxas info    : Compiling entry function '_Z11decrypt_vmkiPiPhS0_iiiiijjjji' for 'sm_61'
ptxas info    : Function properties for _Z11decrypt_vmkiPiPhS0_iiiiijjjji
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 63 registers, 400 bytes cmem[0], 324 bytes cmem[2], 2 textures
cuda_attack.cu:40:42: warning: comparison of constant 4294967168 with expression
      of type 'unsigned char' is always false
      [-Wtautological-constant-out-of-range-compare]
if (((outPsw[i]) == 128) || ((outPsw[i]) == 4294967168U)) { (outPsw[i]) ...
                             ~~~~~~~~~~~ ^  ~~~~~~~~~~~
1 warning generated.
ptxas info    : 0 bytes gmem, 12584 bytes cmem[3]
utils.cu:305:16: warning: implicit conversion from 'int' to 'char' changes value
      from 128 to -128 [-Wconstant-conversion]
(tmp[size]) = (128); 
            ~  ^~~
1 warning generated.
ptxas info    : 0 bytes gmem, 12584 bytes cmem[3]
ptxas info    : Compiling entry function '_Z16w_block_evaluatePhiS_Pj' for 'sm_61'
ptxas info    : Function properties for _Z16w_block_evaluatePhiS_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 352 bytes cmem[0], 4 bytes cmem[2]

====== Build BitCracker OpenCL version ======
rm -rf *.o
rm -rf bitcracker_opencl
gcc -I/usr/include -L/usr/lib64 -L/usr/lib -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -cl-std=CL1.2 -O3 -Wextra -o bitcracker_opencl main.c opencl_attack.c utils.c w_blocks.c -lOpenCL
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206:
/usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not
      supported in OpenCL
    #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
                                                          ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not
      supported in OpenCL
    #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
                                                         ^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not
      supported in OpenCL
    #define __swift_compiler_version_at_least(...) 1
                                              ^
In file included from main.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in
      OpenCL
    #define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,_...
                            ^
/usr/include/Availability.h:434:30: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO(__VA_AR...
                             ^
/usr/include/Availability.h:435:47: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED_WITH_REPLACEMENT(...) __API_DEPRECATED_REP_...
                                              ^
/usr/include/Availability.h:445:31: error: variadic macros not supported in
      OpenCL
    #define __API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS...
                              ^
In file included from main.c:22:
In file included from ./bitcracker.h:22:
/usr/include/stdio.h:67:14: error: extern variable must reside in constant
      address space
extern FILE *__stdinp;
             ^
/usr/include/stdio.h:68:14: error: extern variable must reside in constant
      address space
extern FILE *__stdoutp;
             ^
/usr/include/stdio.h:69:14: error: extern variable must reside in constant
      address space
extern FILE *__stderrp;
             ^
/usr/include/stdio.h:155:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fprintf(FILE * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:161:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fscanf(FILE * __restrict, const char * __restrict, ...) __scanf...
         ^
/usr/include/stdio.h:177:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      scanf(const char * __restrict, ...) __scanflike(1, 2);
         ^
/usr/include/stdio.h:180:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sprintf(char * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:181:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sscanf(const char * __restrict, const char * __restrict, ...) _...
         ^
/usr/include/stdio.h:338:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      snprintf(char * __restrict __str, size_t __size, const char * _...
         ^
/usr/include/stdio.h:356:5: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int     dprintf(int, const char * __restrict, ...) __printflike(2, 3) __...
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
In file included from opencl_attack.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206:
/usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not
      supported in OpenCL
    #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
                                                          ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not
      supported in OpenCL
    #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
                                                         ^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not
      supported in OpenCL
    #define __swift_compiler_version_at_least(...) 1
                                              ^
In file included from opencl_attack.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in
      OpenCL
    #define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,_...
                            ^
/usr/include/Availability.h:434:30: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO(__VA_AR...
                             ^
/usr/include/Availability.h:435:47: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED_WITH_REPLACEMENT(...) __API_DEPRECATED_REP_...
                                              ^
/usr/include/Availability.h:445:31: error: variadic macros not supported in
      OpenCL
    #define __API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS...
                              ^
In file included from opencl_attack.c:22:
In file included from ./bitcracker.h:22:
/usr/include/stdio.h:67:14: error: extern variable must reside in constant
      address space
extern FILE *__stdinp;
             ^
/usr/include/stdio.h:68:14: error: extern variable must reside in constant
      address space
extern FILE *__stdoutp;
             ^
/usr/include/stdio.h:69:14: error: extern variable must reside in constant
      address space
extern FILE *__stderrp;
             ^
/usr/include/stdio.h:155:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fprintf(FILE * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:161:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fscanf(FILE * __restrict, const char * __restrict, ...) __scanf...
         ^
/usr/include/stdio.h:177:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      scanf(const char * __restrict, ...) __scanflike(1, 2);
         ^
/usr/include/stdio.h:180:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sprintf(char * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:181:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sscanf(const char * __restrict, const char * __restrict, ...) _...
         ^
/usr/include/stdio.h:338:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      snprintf(char * __restrict __str, size_t __size, const char * _...
         ^
/usr/include/stdio.h:356:5: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int     dprintf(int, const char * __restrict, ...) __printflike(2, 3) __...
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
In file included from utils.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206:
/usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not
      supported in OpenCL
    #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
                                                          ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not
      supported in OpenCL
    #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
                                                         ^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not
      supported in OpenCL
    #define __swift_compiler_version_at_least(...) 1
                                              ^
In file included from utils.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in
      OpenCL
    #define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,_...
                            ^
/usr/include/Availability.h:434:30: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO(__VA_AR...
                             ^
/usr/include/Availability.h:435:47: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED_WITH_REPLACEMENT(...) __API_DEPRECATED_REP_...
                                              ^
/usr/include/Availability.h:445:31: error: variadic macros not supported in
      OpenCL
    #define __API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS...
                              ^
In file included from utils.c:22:
In file included from ./bitcracker.h:22:
/usr/include/stdio.h:67:14: error: extern variable must reside in constant
      address space
extern FILE *__stdinp;
             ^
/usr/include/stdio.h:68:14: error: extern variable must reside in constant
      address space
extern FILE *__stdoutp;
             ^
/usr/include/stdio.h:69:14: error: extern variable must reside in constant
      address space
extern FILE *__stderrp;
             ^
/usr/include/stdio.h:155:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fprintf(FILE * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:161:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fscanf(FILE * __restrict, const char * __restrict, ...) __scanf...
         ^
/usr/include/stdio.h:177:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      scanf(const char * __restrict, ...) __scanflike(1, 2);
         ^
/usr/include/stdio.h:180:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sprintf(char * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:181:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sscanf(const char * __restrict, const char * __restrict, ...) _...
         ^
/usr/include/stdio.h:338:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      snprintf(char * __restrict __str, size_t __size, const char * _...
         ^
/usr/include/stdio.h:356:5: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int     dprintf(int, const char * __restrict, ...) __printflike(2, 3) __...
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
In file included from w_blocks.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
In file included from /usr/include/Availability.h:206:
/usr/include/AvailabilityInternal.h:33241:59: error: variadic macros not
      supported in OpenCL
    #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
                                                          ^
/usr/include/AvailabilityInternal.h:33272:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_MSG_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33285:67: error: variadic macros not
      supported in OpenCL
    #define __API_DEPRECATED_REP_GET_MACRO(_1,_2,_3,_4,_5,_6,NAME,...) NAME
                                                                  ^
/usr/include/AvailabilityInternal.h:33307:58: error: variadic macros not
      supported in OpenCL
    #define __API_UNAVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
                                                         ^
/usr/include/AvailabilityInternal.h:33348:47: error: variadic macros not
      supported in OpenCL
    #define __swift_compiler_version_at_least(...) 1
                                              ^
In file included from w_blocks.c:22:
In file included from ./bitcracker.h:22:
In file included from /usr/include/stdio.h:64:
In file included from /usr/include/_stdio.h:69:
/usr/include/Availability.h:415:29: error: variadic macros not supported in
      OpenCL
    #define __API_AVAILABLE(...) __API_AVAILABLE_GET_MACRO(__VA_ARGS__,_...
                            ^
/usr/include/Availability.h:434:30: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO(__VA_AR...
                             ^
/usr/include/Availability.h:435:47: error: variadic macros not supported in
      OpenCL
    #define __API_DEPRECATED_WITH_REPLACEMENT(...) __API_DEPRECATED_REP_...
                                              ^
/usr/include/Availability.h:445:31: error: variadic macros not supported in
      OpenCL
    #define __API_UNAVAILABLE(...) __API_UNAVAILABLE_GET_MACRO(__VA_ARGS...
                              ^
In file included from w_blocks.c:22:
In file included from ./bitcracker.h:22:
/usr/include/stdio.h:67:14: error: extern variable must reside in constant
      address space
extern FILE *__stdinp;
             ^
/usr/include/stdio.h:68:14: error: extern variable must reside in constant
      address space
extern FILE *__stdoutp;
             ^
/usr/include/stdio.h:69:14: error: extern variable must reside in constant
      address space
extern FILE *__stderrp;
             ^
/usr/include/stdio.h:155:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fprintf(FILE * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:161:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      fscanf(FILE * __restrict, const char * __restrict, ...) __scanf...
         ^
/usr/include/stdio.h:177:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      scanf(const char * __restrict, ...) __scanflike(1, 2);
         ^
/usr/include/stdio.h:180:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sprintf(char * __restrict, const char * __restrict, ...) __prin...
         ^
/usr/include/stdio.h:181:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      sscanf(const char * __restrict, const char * __restrict, ...) _...
         ^
/usr/include/stdio.h:338:6: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int      snprintf(char * __restrict __str, size_t __size, const char * _...
         ^
/usr/include/stdio.h:356:5: error: invalid prototype, variadic arguments are not
      allowed in OpenCL
int     dprintf(int, const char * __restrict, ...) __printflike(2, 3) __...
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [all] Error 1

====== Executables in build directory ======

**Comment by stevenliuit** [comment]
i build src_CUDA successs but i build src_OpenCL error.
But now you can calculate。
StevendeiMac:bitcracker stevenbiu$ ./build/bitcracker_cuda -f ./test_hash/hash_recv_pass.txt -d bitcracker_wlrp_0.txt -t 8 -b 24 -g 0 -r

---------> BitCracker: BitLocker password cracking tool <---------


====================================
Selected device: GPU GeForce GTX 1080 Ti (ID: 0)
====================================

Compute capability: 6.1
Clock rate: 1721000
Clock rate: 1721 MHz (1.72 GHz)
Memory Clock Rate (KHz): 5505000
Memory Bus Width (bits): 352
Peak Memory Bandwidth (GB/s): 484.440000
Device copy overlap: Enabled
Async memory engine count: 2
Concurrent kernels: 1
Kernel execition timeout: Enabled
Total global mem:  11810963456 bytes
Free memory: 8940351488 bytes
Texture Alignment:  512
Multiprocessor count:  28
Shared mem per mp:  49152
Registers per mp:  65536
Threads in warp:  32
Max threads per block:  1024
Max thread dimensions:  (1024, 1024, 64)
Max grid dimensions:  (2147483647, 65535, 65535)

For this session, BitCracker requires at least 293601280 bytes of memory

====================================
Retrieving Info
====================================

Reading hash file "./test_hash/hash_recv_pass.txt"
$bitlocker$2$16$df4d3254aa7554fa0b02509876bf11eb$1048576$12$6070c179822fd20106000000$60$38cf5f73b5b8fb90713f0ea203427ad01ac7bf95cf7efd194d907d152ba09ec412809236d8ef65da95d6ff6ba51832f50af757f3a9c706e939b5faae


====================================
Attack
====================================

Type of attack: Recovery Password
CUDA Threads: 1024
CUDA Blocks: 24
Psw per thread: 8
Max Psw per kernel: 196608
Dictionary: bitcracker_wlrp_0.txt
Strict Check (-s): No
MAC Comparison (-m): No

CUDA Kernel execution:
	Effective passwords: 196608
	Passwords Range:
		000000-000011-000022-000033-000044-000055-008459-015180
		.....
		000000-000011-000022-000033-000044-000055-008492-015400
	Time: 120.819180 sec
	Passwords x second:  1627.29 pw/sec


high speed aha。

**Comment by stevenliuit** [comment]
![image](https://user-images.githubusercontent.com/4044994/44860607-3ac15780-aca9-11e8-9242-19f58529b6da.png)

**Comment by e-ago** [comment]
On my Mac I'm using `clang -framework OpenCL -o bitcracker_opencl main.c opencl_attack.c utils.c w_blocks.c` instead of `gcc $(MAKE_INCLUDE) $(FLAGS) -o bitcracker_opencl main.c opencl_attack.c utils.c w_blocks.c -lOpenCL`. You can try it too. Anyway, the CUDA implementation is the best one, so I'm glad that you were able to build and run the attack. I can see that performance on your Pascal are even higher than mine reported on the main page :)

Let me know if you'll find the correct recovery password!
