### ISSUE TITLE
Extract image file

### ISSUE THREAD

**Issue by stevenliuit** [e-ago/bitcracker#9]
I use the command to extract all the images of the disk to generate the hash, or do I need to extract the part to generate the hash?

**Comment by e-ago** [comment]
Ideally you shold extract the image of the entire encrypted volume but if you know where (the offset) the signature `-FVE-FV-` is you can extract only that part. Once `bitcracker_hash` created the hash, you need the image file no more.

**Comment by stevenliuit** [comment]
thank you
